services:
  api:
    build: .
    # En producción usa la imagen de Docker Hub:
    # image: villabos/analytics-service:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8002:8002"
