services:
  analytics_api:
    image: villabos/analytics-service:v1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8002:8002"

networks:
  default:
    name: proycloud_net
